### ISSUE TITLE
Access Denied problem

### ISSUE THREAD

**Issue by cyberbandityt** [usmannaushahi/usb_thermal_printer_web#3]
I used my bixolon SRP-E302 to print using the package. However, I got this error.

Error: SecurityError: Failed to execute 'open' on 'USBDevice': Access denied.

**Comment by zenosama1111** [comment]
I have the same issue.

**Comment by Ant0nidass** [comment]
same here, maybe there is another library, that works?

**Comment by usmannaushahi** [comment]
Please refer to this comment: https://github.com/usmannaushahi/usb_thermal_printer_web/issues/4#issuecomment-2505429632
