### ISSUE TITLE
permission request

### ISSUE THREAD

**Issue by aemsoftwarearacatuba** [usmannaushahi/usb_thermal_printer_web#4]
Erro Message:
SecurityError: Failed to execute 'requestDevice' on 'USB': Must be handling a user gesture to show a permission request.

When running flutterweb, when trying to connect a USB device in the function: await printer.pairDevice(vendorId: 0x20D1, productId: 0x7008);

Permission error occurs. How can I solve this type of problem?

I'm using Chrome and Windows 10.

**Comment by Ant0nidass** [comment]
DId you solved this problem? 
I get "RethrownDartError: SecurityError: Failed to execute 'open' on 'USBDevice': Access denied." when I try example code snippet.
Tried to install WinUSB driver, but no effect.

**Comment by Aslamabdulla** [comment]
@aemsoftwarearacatuba @Ant0nidass I fixed it by reinstalling the printer driver using Zadig.
